# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencias', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_de_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('lbl', 'Libras'), ('tnl', 'Toneladas Largas'), ('tnm', 'Toneladas Metricas'), ('tnc', 'Toneladas Cortas'), ('g', 'Gramos'), ('u', 'Unidades'), ('lt', 'Litros'), ('gal', 'Galones'), ('bar', 'Barriles'), ('lts', 'Latas'), ('caj', 'Cajas'), ('mil', 'Millares'), ('m3', 'Metros cúbicos'), ('m', 'Metros'), ('o', 'Otros')], default='u', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDeExistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('observaciones', models.TextField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['fecha_reporte'],
            },
        ),
        migrations.AddField(
            model_name='existencia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='reporte_de_existencia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventario.ReporteDeExistencia'),
        ),
    ]
