# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-12 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180712_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportedeexistencia',
            options={'ordering': ['fecha_reporte']},
        ),
        migrations.AddField(
            model_name='reportedeexistencia',
            name='observaciones',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('lbl', 'Libras'), ('tnl', 'Toneladas Largas'), ('tnm', 'Toneladas Metricas'), ('tnc', 'Toneladas Cortas'), ('g', 'Gramos'), ('u', 'Unidades'), ('lt', 'Litros'), ('gal', 'Galones'), ('bar', 'Barriles'), ('lts', 'Latas'), ('caj', 'Cajas'), ('mil', 'Millares'), ('m3', 'Metros cúbicos'), ('m', 'Metros'), ('o', 'Otros')], default='u', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportedeexistencia',
            name='fecha_reporte',
            field=models.DateField(),
        ),
    ]
