# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlatillo',
            fields=[
                ('idCategoriaPlatillo', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('codigo_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('numero_mesa', models.IntegerField()),
                ('asientos', models.IntegerField()),
                ('ocupado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('codigoPlatillo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('categoria_platillo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platillo', to='restaurant_application.CategoriaPlatillo')),
            ],
        ),
    ]
