# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlatillo',
            fields=[
                ('idCategoriaPlatillo', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
    ]
