# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
