# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('codigoPlatillo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('idCategoriaPlatillo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platillo', to='restaurant_application.CategoriaPlatillo')),
            ],
        ),
    ]
