# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_application', '0002_platillo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='idCategoriaPlatillo',
        ),
        migrations.AddField(
            model_name='platillo',
            name='categoria_platillo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_platillo', to='restaurant_application.CategoriaPlatillo'),
        ),
    ]
