# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_application', '0003_auto_20180711_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='categoria_platillo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platillo', to='restaurant_application.CategoriaPlatillo'),
        ),
    ]
