# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_de_venta', models.FloatField()),
                ('comentario', models.CharField(max_length=128)),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Platillo')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now=True)),
                ('descuento', models.FloatField(blank=True)),
                ('propina', models.FloatField(default=0.1)),
                ('estado', models.CharField(max_length=20)),
                ('comentario', models.TextField(max_length=512)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Caja')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_de_perfil', models.ImageField(blank=True, upload_to='profile_pics')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Empleado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(null=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_real', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='procesos.Sesion'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_de_orden', to='procesos.Orden'),
        ),
    ]
