# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_application', '0002_caja_cliente'),
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='cantidad',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='comentario',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='consumible',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Platillo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_de_orden', to='procesos.Orden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='precio_de_venta',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Caja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='comentario',
            field=models.TextField(default=None, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='descuento',
            field=models.FloatField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='mesa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Mesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='mesero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='propina',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='orden',
            name='sesion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='procesos.Sesion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='caja',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Caja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='cajero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant_application.Empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='estado',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='monto_apertura',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='monto_real',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
