# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='monto_real',
            field=models.FloatField(blank=True),
        ),
    ]
