# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='descuento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(default='No Finalizado', max_length=20),
        ),
    ]
