# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_auto_20180714_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='monto_apertura',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='monto_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
