# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_detalleorden_ordenados'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='numero_orden',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
