# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_auto_20180715_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fecha_cierre',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='monto_real',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
