# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-20 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_orden_numero_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='ordenados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orden',
            name='numero_orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='procesos.Orden'),
        ),
    ]
