# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_auto_20180720_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='ordenados',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
