# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0005_auto_20180721_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='entregado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
