# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_detalleorden_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='descuento',
            field=models.FloatField(default=0, null=True),
        ),
    ]
