# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_auto_20180721_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleorden',
            old_name='entregado',
            new_name='entregados',
        ),
    ]
